name: "Clemens Ager"           #Author name
profile: "hello world"
github: ""         #Github username
gitlab: ""         #Gitlab username
linkedin: ""       #LinkedIn username
facebook: ""       #Facebook username
twitter: ""        #Twitter username
instagram: ""      #Instagram username
stackoverflow: ""  #StackOverflow username
devto: ""          #Dev.to username 
