 main:
  - name: Blog
    url: /
    weight: 1
  - name: Projects
    url: /project/
    weight: 2
  - name: Contact
    url: /page/contact/
    weight: 6
  - name: About
    url: /page/about/
    weight: 5
  - name: Publications
    url: /publication/
    weight: 4
