main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Publications
    url: /publication/
    weight: 4
  - name: About Me
    url: /authors/c-ager
    weight: 20 
  - name: Docs
    url: /docs/
    weight: 3
