mainSections:
  - post
intro: true
headline: Clemens' Notes
description: Personal Blog
github: "https://github.com/bdcaf"
#gitlab: "https://gitlab.com/XXX"
linkedin: "https://www.linkedin.com/in/clemens-ager-1228a295/"
twitter: "https://twitter.com/c_decaf"
stackoverflow: "https://stackoverflow.com/users/471614/bdecaf"
#facebook: "https://www.facebook.com/username"
email: clemens.ager@gmail.com
opengraph: true
shareTwitter: true
rss: true
shareFacebook: false
shareLinkedIn: false
dateFormat: "Mon, Jan 2, 2006"
exponeaJsUrl: ""
exponeaTarget: ""
exponeaToken: ""
exponeaTrackVisits: false
readingTime: true
readingTimeText: "Estimated reading time:"
fathomUrl: ""
fathomSiteId: ""
# If you want to use plausible(https://plausible.io) for analytics, add this section
plausibleAnalytics:
  domain: ""
  # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
  serverURL: ""
