baseurl = "http://homepage.uibk.ac.at/~c1891011/"
languageCode = "de-at"
title = "Clemens Ager"
theme = "vienna"
# Copyright notice. This is displayer in the footer.
copyright = "Inhaber: Clemens Ager, Brixlegg, 2015"

Paginate = 10

[params]
	name = "Clemens Ager"
	description = "Rechenknecht, Student"
	authorlocation = "Tirol"
	email = "clemens.ager@uibk.ac.at"
    logo = "images/logo.png"

	# Social accounts. Link to these accounts are displayed in the header and footer.
	twitter = "c_decaf"
	github = "bdcaf"
	linkedin = "https://at.linkedin.com/pub/clemens-ager/95/8a2/122"
	#linkedin = "at.linkedin.com/pub/clemens-ager/95/8a2/122"
	stackoverflow = "471614"
	#keybase = "Your keybase.io username"
	# Google Analytics API key.
	#ga_api_key = "Your Google Analytics tracking id"
	# Mixpanel API key.
	#mixpanel_api_key = "Your Mixpanel API key"
	author = "Clemens Ager"
	avatar = "/~c1891011/img/avatar.jpg"
	contact = "mailto:clemens.ager@uibk.ac.at"
	bio = "Rechenknecht // Student" # Short subtitle/tagline.  This is displayed in the header.  
	subtitle = "Sammlung von Nützlichem und Kuriosem"
	#themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

#https://www.linkedin.com/pub/clemens-ager/95/8a2/122

[blackfriday]
  fractions = false

# vim: fdm=marker : 
