Languages:
  de:
    languageCode: de
    menu:
      main:
      - name: Über
        url: '#about.de'
        weight: 1
      - name: Posts
        url: '#posts.de'
        weight: 2
      - name: Publikationen
        url: '#publications_selected.de'
        weight: 3
      - name: Projects
        url: '#projects.de'
        weight: 4
      - name: Kontakt
        url: '#contact.de'
        weight: 6
    organization: Universität Innsbruck
    role: Rechenknecht // Doktoranwärter // Physiker
    weight: 2
  en:
    languageCode: en
    organization: University Innsbruck
    role: Number Cruncher // PhD Candidate // Physicist
    weight: 1

MetaDataFormat: yaml
Paginate: 30
PaginatePath: ''
author: Clemens Ager
baseurl: https://bdcaf.github.io/
blackfriday:
  hrefTargetBlank: true
builddrafts: false
canonifyurls: true
contentdir: content
copyright: Clemens Ager, Brixlegg
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
disqusshortname: ''
editor: nvim
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
- \.sh$
- \.tmp$
- \.txt
- \.old
- \.DS_Store
layoutdir: layouts
menu:
  main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: '#posts'
    weight: 2
  - name: Publications
    url: '#publications_selected'
    weight: 3
  - name: Projects
    url: '#projects'
    weight: 4
  - name: Contact
    url: '#contact'
    weight: 6
newContentEditor: nvim
params:
  address: Innrain 66, 6020 Innsbruck
  author: Clemens Ager
  authorlocation: Tirol
  avatar: my_portrait.png
  bio_twitter: c_decaf
  cachebuster: true
  contact: mailto:clemens.ager@uibk.ac.at
  custom_css: []
  custom_js: []
  date_format: '2006-01-02'
  dateformfull: Mon  2. Jan 2006 15:04:05 MST
  description: Rechenknecht, Student
  email: clemens.ager@uibk.ac.at
  github: bdcaf
  highlightjs: false
  lang: en
  linkedin: clemens-ager-1228a295
  math: false
  name: Clemens Ager
  sharing: false
  social:
  - fa_class: far fa-envelope
    link: mailto:clemens.ager@uibk.ac.at
  - fa_class: fab fa-twitter
    link: //twitter.com/c_decaf
  - fa_class: fas fa-graduation-cap
    link: https://scholar.google.co.uk/citations?user=Agq35HgAAAAJ
  - fa_class: fab fa-github-square
    link: https://github.com/bdcaf
  - fa_class: fab fa-linkedin
    link: https://at.linkedin.com/in/clemens-ager-1228a295
  subtitle: Sammlung von Nützlichem und Kuriosem
  twitter: c_decaf
permalinks:
  post: /:year/:month/:day/:slug
pluralizelisttitles: true
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true
publishdir: public
pygmentsuseclasses: true
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 90
  - name: sections
    weight: 80
  - name: date
    weight: 10
  toLower: true
title: C. Ager
