baseurl = "https://bdcaf.github.io/"
author = "Clemens Ager"
title = "C. Ager"
#theme = "hugo-academic"
# Copyright notice. This is displayed in the footer.
copyright = "Clemens Ager, Brixlegg"
MetaDataFormat = "yaml"

ignoreFiles = [ "\\.sh$", "\\.tmp$", "\\.txt", "\\.old", "\\.DS_Store"]
editor = "nvim"
newContentEditor = "nvim"

footnotereturnlinkcontents = "<sup>^</sup>"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

Paginate = 30
PaginatePath = ""

builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
disqusshortname = ""
pluralizelisttitles = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
name = "Clemens Ager"
author = "Clemens Ager"
address = "Innrain 66, 6020 Innsbruck"
bio_twitter = "c_decaf" 
description = "Rechenknecht, Student"
subtitle = "Sammlung von Nützlichem und Kuriosem"
authorlocation = "Tirol"
email = "clemens.ager@uibk.ac.at"

math = false
sharing = false

# Social accounts. Link to these accounts are displayed in the header and footer.
#keybase = "Your keybase.io username"
#avatar = "portrait2.jpg"
avatar = "my_portrait.png"
contact = "mailto:clemens.ager@uibk.ac.at"
linkedin = "clemens-ager-1228a295"
github = "bdcaf"
twitter = "c_decaf"

cachebuster = true
date_format = "2006-01-02"
dateformfull = "Mon  2. Jan 2006 15:04:05 MST"
highlightjs = false
lang = "en"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = []
custom_js  = []

[blackfriday]
hrefTargetBlank = true

[[params.social]]
fa_class = "far fa-envelope"
link = "mailto:clemens.ager@uibk.ac.at"

[[params.social]]
fa_class = "fab fa-twitter"
link = "//twitter.com/c_decaf"

[[params.social]]
fa_class = "fas fa-graduation-cap"
link = "https://scholar.google.co.uk/citations?user=Agq35HgAAAAJ"

[[params.social]]
fa_class = "fab fa-github-square"
link = "https://github.com/bdcaf"

[[params.social]]
fa_class = "fab fa-linkedin"
link = "https://at.linkedin.com/in/clemens-ager-1228a295"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
#{{{
# {{{
[[menu.main]]
name = "About"
url = "#about"
weight = 1

[[menu.main]]
name = "Posts"
url = "#posts"
weight = 2

[[menu.main]]
name = "Publications"
url = "#publications_selected"
weight = 3

[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4

#[[menu.main]]
#name = "Teaching"
#url = "#teaching"
#weight = 5

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6
# }}}
# {{{
[[Languages.de.menu.main]]
name = "Über"
url = "#about.de"
weight = 1

[[Languages.de.menu.main]]
name = "Posts"
url = "#posts.de"
weight = 2

[[Languages.de.menu.main]]
name = "Publikationen"
url = "#publications_selected.de"
weight = 3

[[Languages.de.menu.main]]
name = "Projects"
url = "#projects.de"
weight = 4

[[Languages.de.menu.main]]
name = "Kontakt"
url = "#contact.de"
weight = 6
# }}}
# }}}

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Configure the English version of the website.
[Languages]
[Languages.en]
weight = 1
languageCode = "en"
role = "Number Cruncher // PhD Candidate // Physicist"
organization = "University Innsbruck"

[Languages.de]
languageCode = "de"
weight = 2
role = "Rechenknecht // Doktoranwärter // Physiker"
organization = "Universität Innsbruck"

# vim: fdm=marker : 
