baseurl = "//homepage.uibk.ac.at/~c1891011/"
author = "Clemens Ager"
title = "Clemens Ager"
theme = "academic"
# Copyright notice. This is displayer in the footer.
copyright = "Inhaber: Clemens Ager, Brixlegg, 2015"
MetaDataFormat = "yaml"

ignoreFiles = [ "\\.sh$", "\\.tmp$", "\\.txt", "\\.old", "\\.DS_Store"]

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

Paginate = 10
PaginatePath = ""

builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
pygmentsuseclasses = true
disqusshortname = ""
pluralizelisttitles = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
name = "Clemens Ager"
role = "Number Cruncher // PhD Candidate // Physicist"
organization = "University Innsbruck"
author = "Clemens Ager"
address = "Innrain 66, 6020 Innsbruck"
bio = "Rechenknecht //Student" # Short subtitle/tagline.  This is displayed in the header.  
bio_full = "Clemens Ager: Rechenknecht"
bio_twitter = "c_decaf" 
description = "Rechenknecht, Student"
subtitle = "Sammlung von Nützlichem und Kuriosem"
authorlocation = "Tirol"
email = "clemens.ager@uibk.ac.at"

math = false
sharing = false

# Social accounts. Link to these accounts are displayed in the header and footer.
#keybase = "Your keybase.io username"
avatar = "avatar.png"
contact = "mailto:clemens.ager@uibk.ac.at"
linkedin = "clemens-ager-1228a295"
github = "bdcaf"
twitter = "c_decaf"

cachebuster = true
date_format = "2006-01-02"
dateformfull = "Mon  2. Jan 2006 15:04:05 MST"
highlightjs = true
#lang = "en"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["cle.css"]
custom_js  = []

[blackfriday]
hrefTargetBlank = true

[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:clemens.ager@uibk.ac.at"

[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/c_decaf"

[[params.social]]
icon = "google-scholar"
icon_pack = "ai"
link = "https://scholar.google.co.uk/citations?user=Agq35HgAAAAJ"

[[params.social]]
icon = "github"
icon_pack = "fa"
link = "//github.com/bdcaf"

[[params.social]]
icon = "linkedin"
icon_pack = "fa"
link = "//at.linkedin.com/in/clemens-ager-1228a295"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
name = "About"
url = "#about"
weight = 1

[[menu.main]]
name = "Posts"
url = "#posts"
weight = 2

[[menu.main]]
name = "Publications"
url = "#publications_selected"
weight = 3

[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4

#[[menu.main]]
#name = "Teaching"
#url = "#teaching"
#weight = 5

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6

# Configure the English version of the website.
[Languages]
[Languages.en]
weight = 1
languageCode = "en-uk"
[Languages.de]
languageCode = "de-at"
weight = 2

# vim: fdm=marker : 
