rules:
  at-rule-no-unknown: true
  block-no-empty: true
  color-hex-case: "lower"
  color-named: "always-where-possible"
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-trailing-semicolon: "always"
  declaration-colon-space-after: "always"
  declaration-colon-space-before: "never"
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-url-quotes: "always"
  keyframe-declaration-no-important: true
  media-feature-name-no-unknown: true
  media-feature-range-operator-space-after: "always"
  media-feature-range-operator-space-before: "always"
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  property-no-unknown: true
  selector-combinator-space-after: "always"
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: "double"
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  string-no-newline: true
  string-quotes: "double"
  unit-no-unknown: true
